language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "5.3"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: precise
    - php: "5.4"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
    - php: "5.5"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
    - php: "5.6"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.0"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.1"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.2"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "nightly"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "master"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "hhvm"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
  allow_failures:
    - php: "master"
    - php: "hhvm"

install:
    - composer self-update
    - if [[ $USE_PSALM -eq 1 ]]; then composer require --dev "vimeo/psalm:1.1.4|2.0.5"; fi
    - composer update

script:
    - travis_wait 30 vendor/bin/phpunit
    - if [[ $CHECK_MBSTRING -eq 1 ]]; then travis_wait 30 php -dmbstring.func_overload=7 vendor/bin/phpunit; fi
    - vendor/bin/phpunit --bootstrap autoload-fast.php
    - if [[ $CHECK_MBSTRING -eq 1 ]]; then travis_wait 30 php -dmbstring.func_overload=7 vendor/bin/phpunit --bootstrap autoload-fast.php; fi
    - if [[ $USE_PSALM -eq 1 ]]; then vendor/bin/psalm; fi
