language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "5.3"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: precise
    - php: "5.4"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: trusty
    - php: "5.5"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: trusty
    - php: "5.6"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.0"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.1"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.2"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "7.3"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "nightly"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "master"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "hhvm"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
  allow_failures:
    - php: "nightly"
    - php: "master"
    - php: "hhvm"

install:
    - if [[ $USE_PSALM -eq 1 ]]; then composer require --dev "vimeo/psalm:^1|^2"; fi
    - composer update
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == 7.3 ]]; then composer require --dev "phpstan/phpstan:^0.11.5"; fi
    - chmod +x tests/polyfill_test.sh

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == 7.3 ]]; then vendor/bin/phpstan analyze; fi
    - travis_wait 30 vendor/bin/phpunit
    - if [[ $CHECK_MBSTRING -eq 1 ]]; then travis_wait 30 php -dmbstring.func_overload=7 vendor/bin/phpunit; fi
    - vendor/bin/phpunit --bootstrap autoload-fast.php
    - if [[ $CHECK_MBSTRING -eq 1 ]]; then travis_wait 30 php -dmbstring.func_overload=7 vendor/bin/phpunit --bootstrap autoload-fast.php; fi
    - if [[ $USE_PSALM -eq 1 ]]; then vendor/bin/psalm; fi
    - tests/polyfill_test.sh
