language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "5.2"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: precise
    - php: "5.3"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: precise
    - php: "5.4"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: trusty
    - php: "5.5"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: trusty
    - php: "5.6"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.0"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.1"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.2"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "7.3"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "7.4snapshot"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "nightly"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=0
    - php: "master"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=0
    - php: "hhvm"
      os: linux
      env: USE_PSALM=0
           CHECK_MBSTRING=1
  allow_failures:
    - php: "nightly"
    - php: "master"
    - php: "hhvm"

install:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]] && [[ $USE_PSALM -eq 1 ]]; then composer require --dev "phpunit/phpunit:^7"; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then `phpenv global 5.3.29`; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then cat composer-php52.json > composer.json; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]] && [[ $USE_PSALM -eq 1 ]]; then composer require --dev "vimeo/psalm:^3.6"; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.4" ]] && [[ $USE_PSALM -eq 1 ]]; then composer require --dev "vimeo/psalm:^1|^2"; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then `cp psalm-above-3.xml psalm.xml`; else `cp psalm-below-3.xml psalm.xml`; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then chmod +x tests/fix-php52.sh; fi
    - gitcommit=$(git rev-parse HEAD) && composer config autoloader-suffix "$gitcommit"
    - composer update
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then tests/fix-php52.sh; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == 7.3 ]]; then composer require --dev "phpstan/phpstan:^0.11.5"; fi
    - chmod +x tests/polyfill_test.sh
    - chmod +x tests/travis-php52.sh
    - chmod +x tests/travis.sh
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then `phpenv global "$TRAVIS_PHP_VERSION"`; fi

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then vendor/bin/phpstan analyze; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then travis_wait 60 tests/travis-php52.sh; else travis_wait 30 tests/travis.sh; fi
    - if [[ $USE_PSALM -eq 1 ]]; then vendor/bin/psalm; fi
    - tests/polyfill_test.sh
